### ISSUE TITLE
Version Requirement?

### ISSUE THREAD

**Issue by larshp** [d023604/open-location-code-abap#2]
Hi,
Whats the version requirement to run this?

https://github.com/d023604/open-location-code-abap/blob/main/src/zcl_open_location_code.clas.abap#L547

doesn't seem to compile on either 751 or 752,

![image](https://user-images.githubusercontent.com/5888506/95654014-4ecd1980-0afd-11eb-9bdb-37cd0216ff36.png)

**Comment by andrew-barnard** [comment]
Hello Lars,
I have updated the repo a version that runs on 750. I have also deleted the code from an ABAP system, then download from this repo and successfully installed under abapGit 1.100.0. No syntax errors reported and unit tests passing. 
Thank you for trying to install and sorry to have wasted your time. 
Andrew

**Comment by larshp** [comment]
thanks

I didnt install it just looked to see if there were any false positives detected by abaplint 😄
